/* 판매번호 */
CREATE SEQUENCE SALENO_SEQ 
	MINVALUE 1
	MAXVALUE 99999
	INCREMENT BY 1
	START WITH 1
	ORDER;

/* 시퀀스 */
CREATE SEQUENCE STORE_SEQ 
	MINVALUE 1
	MAXVALUE 99999
	INCREMENT BY 1
	START WITH 1
	ORDER;

/* 제품 */
CREATE TABLE MED_Product (
	CODE NUMBER NOT NULL, /* 상품코드 */
	NAME VARCHAR2(100) NOT NULL, /* 상품명 */
	MADEBY VARCHAR2(50) NOT NULL, /* 제조사 */
	INPRICE NUMBER NOT NULL, /* 단가 */
	OUTPRICE NUMBER NOT NULL, /* 판매가 */
	STORED NUMBER NOT NULL /* 재고 */
);

ALTER TABLE MED_Product
	ADD
		CONSTRAINT PK_MED_Product
		PRIMARY KEY (
			CODE
		);

/* 판매 */
CREATE TABLE MED_Sale (
	SALENO NUMBER NOT NULL, /* 판매번호 */
	CODE NUMBER NOT NULL, /* 상품코드 */
	SALE_QUANTITY NUMBER NOT NULL, /* 판매갯수 */
	SALE_DATE DATE NOT NULL, /* 판매일시 */
	SALE_STATUS CHAR DEFAULT 'S' NOT NULL /* 처리상황 */
);

ALTER TABLE MED_Sale
	ADD
		CONSTRAINT PK_MED_Sale
		PRIMARY KEY (
			SALENO,
			CODE
		);

/* 입고 */
CREATE TABLE MED_Store (
	STORENO NUMBER NOT NULL, /* 입고번호 */
	CODE NUMBER NOT NULL, /* 상품코드 */
	STORE_QUANTITY NUMBER NOT NULL, /* 입고갯수 */
	STORE_DATE DATE NOT NULL, /* 입고일시 */
	STORE_STATUS CHAR DEFAULT 'I' NOT NULL /* 입고상황 */
);

ALTER TABLE MED_Store
	ADD
		CONSTRAINT PK_MED_Store
		PRIMARY KEY (
			STORENO,
			CODE
		);

ALTER TABLE MED_Sale
	ADD
		CONSTRAINT FK_MED_Product_TO_MED_Sale
		FOREIGN KEY (
			CODE
		)
		REFERENCES MED_Product (
			CODE
		);

ALTER TABLE MED_Store
	ADD
		CONSTRAINT FK_MED_Product_TO_MED_Store
		FOREIGN KEY (
			CODE
		)
		REFERENCES MED_Product (
			CODE
		);