CREATE TABLE ACADEMY_A (
    STUDENT_NO NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(20) NOT NULL
);
INSERT INTO ACADEMY_A VALUES (1001, '정소화');
INSERT INTO ACADEMY_A VALUES (1002, '김용욱');
INSERT INTO ACADEMY_A VALUES (1003, '고명석');
INSERT INTO ACADEMY_A VALUES (1004, '김연아');

CREATE TABLE ACADEMY_B (
    STUDENT_NO NUMBER PRIMARY KEY,
    STUDENT_NAME VARCHAR2(20) NOT NULL
);
INSERT INTO ACADEMY_B VALUES (1003, '고명석');
INSERT INTO ACADEMY_B VALUES (1004, '김연아');
INSERT INTO ACADEMY_B VALUES (1005, '김태환');
INSERT INTO ACADEMY_B VALUES (1006, '이윤아');

-- VIEW.
-- CREATE VIEW 뷰이름 AS (SELECT 테이블쿼리);
-- 일반 쿼리문으로 생성되는 임시 테이블을 이름을 지정해서 저장할 수 있다. 실제로 테이블로 저장되는건 아니고 가상테이블임.
-- 
CREATE VIEW COMMON AS SELECT academy_a.student_name FROM academy_a, academy_b WHERE academy_a.student_no = academy_b.student_no;
